apiVersion: v1
kind: Service
metadata:
  name: my-docker-repo-service
spec:
  selector:
    app: my-docker-repo
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the pod
  type: LoadBalancer  # Expose the service externally (you might need to adjust this based on your setup)
